<script lang="ts">
	let sponsors = [
		{ label: '19th Hole Bar and Grill' },
		{ label: 'Admiral Theater Foundation' },
		{ label: 'Agate Asphalt' },
		{ label: 'Ahoy Kitsap Playland' },
		{ label: 'All In Septic & Excavation' },
		{ label: 'AllCounty Operations' },
		{ label: 'Bagwell Law' },
		{ label: 'Bankrock Corp' },
		{ label: 'BJC Group Inc' },
		{ label: 'Boot Barn' },
		{ label: 'Brothers Powersports' },
		{ label: 'Budget Blinds' },
		{ label: 'C B Farrier Services' },
		{ label: 'C & C Development & Trucking' },
		{ label: 'Camp Union Properties' },
		{ label: 'Cascade Diesel' },
		{ label: 'Cornerstone Cleaning' },
		{ label: "Dana's Heating & Cooling" },
		{ label: 'Destination Harley Davidson' },
		{ label: 'Diane K. Golbeck, PLLC' },
		{ label: 'Fife RV' },
		{ label: 'Geico, Silverdale Office (Kevin Krieger)' },
		{ label: 'Gresham Pump & Drilling' },
		{ label: 'Grey Miles Co' },
		{ label: 'Hanley Constructions' },
		{ label: 'Haselwood Auto Group' },
		{ label: 'Herdman Plumbing' },
		{ label: 'Horsepower Machine' },
		{ label: 'Integrity Roofing & Construction' },
		{ label: 'Jensen Realtor Group' },
		{ label: 'Joyce Construction' },
		{ label: 'Kahn Industries' },
		{ label: 'Kitsap Credit Union' },
		{ label: 'Kitsap Golf and Country Club' },
		{ label: 'Kitsap Roof Pros' },
		{ label: 'Land Title' },
		{ label: 'Lone Star Donuts' },
		{ label: 'Mathews Electric' },
		{ label: 'Mayda Mechanical' },
		{ label: 'Mitchell Lumber' },
		{ label: 'Mountain View Plumbing' },
		{ label: 'Olympic Ridge' },
		{ label: 'Our Place Pub & Eatery' },
		{ label: 'PacWest Motocross' },
		{ label: 'Pendleton Whiskey' },
		{ label: 'Peninsula Community Health Services' },
		{ label: 'Pickett Property Management' },
		{ label: 'PSE' },
		{ label: 'Puget Fence' },
		{ label: 'Rebecca Gore/Windemere' },
		{ label: 'Robison Plumbing' },
		{ label: 'Sandi Johnson - Realtor' },
		{ label: 'Sherlock Equipment' },
		{ label: 'Sound Pest Control' },
		{ label: 'Stokes Auction' },
		{ label: 'Suquamish Clearwater Casino' },
		{ label: 'Talbot Excavating' },
		{ label: "Tim's Home Medical Supplies" },
		{ label: 'Tracyton Public House' },
		{ label: 'Umpqua Bank' },
		{ label: 'Viking Fence' },
		{ label: 'Virginia Mason Franciscan Health' },
		{ label: 'Westbay Auto Parts' },
		{ label: 'Whitworth Excavating' },
		{ label: 'Wilco' }
	];
</script>
